# Generated by Django 4.2.7 on 2026-04-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Día Feriado',
                'verbose_name_plural': 'Días Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('horario_operativo', models.TimeField(help_text='Hora límite del horario operativo (ej: 10:30)')),
                ('dias_dentro_horario', models.PositiveIntegerField(help_text='Días a sumar si la hora de creación es <= horario operativo')),
                ('dias_fuera_horario', models.PositiveIntegerField(help_text='Días a sumar si la hora de creación es > horario operativo')),
                ('dias_reinversion_dentro', models.PositiveIntegerField(help_text='Días a sumar en reinversión si la hora de creación es <= horario operativo')),
                ('dias_reinversion_fuera', models.PositiveIntegerField(help_text='Días a sumar en reinversión si la hora de creación es > horario operativo')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
